apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Values.name }}
data:
  DB_SERVICE_PREFIX_MAPPING: EXAMPLE-POSTGRESQL=DS1
  EXAMPLE_POSTGRESQL_SERVICE_HOST: '{{ default .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc.cluster.local'
  EXAMPLE_POSTGRESQL_SERVICE_PORT: '5432'
  DS1_DRIVER: postgresql
  DS1_NONXA: 'true'
  DS1_URL: 'jdbc:postgresql://{{ default .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc.cluster.local:5432/test'
  DS1_JNDI: 'java:jboss/datasources/KitchenSinkDatasource'
  DS1_DATABASE: test
  DS1_USERNAME: user
  DS1_PASSWORD: password