apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $.Values.name }}-edge
spec:
  to:
    kind: Service
    name: {{ $.Values.name }}
  port:
    targetPort: 8443
  tls:
    certificate: |
      -----BEGIN CERTIFICATE-----
      MIIDuzCCAqOgAwIBAgIEKoyOMTANBgkqhkiG9w0BAQQFADCBjTELMAkGA1UEBhMC
      VVMxETAPBgNVBAgTCFZpcmdpbmlhMRAwDgYDVQQHEwdGYWlyZmF4MQ4wDAYDVQQK
      EwVqYm9zczEPMA0GA1UECxMGcmVkaGF0MTgwNgYDVQQDDC8qLmFwcHMuY2x1c3Rl
      ci0xOGU1LjE4ZTUuc2FuZGJveDIzMy5vcGVudGxjLmNvbTAeFw0yMTAxMjAyMDM5
      MTJaFw00ODA2MDYyMDM5MTJaMIGNMQswCQYDVQQGEwJVUzERMA8GA1UECBMIVmly
      Z2luaWExEDAOBgNVBAcTB0ZhaXJmYXgxDjAMBgNVBAoTBWpib3NzMQ8wDQYDVQQL
      EwZyZWRoYXQxODA2BgNVBAMMLyouYXBwcy5jbHVzdGVyLTE4ZTUuMThlNS5zYW5k
      Ym94MjMzLm9wZW50bGMuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
      AQEAnPzk2KykgHDSmaEKse03Vl7IqFI9LGdNFHwCrFdEPVPi7uUGLWpjZxDJdLrT
      pWT8iVg28MZxDyAubWnUajPddQ2ZTXv6wHPPzpt2sk8hMDF8VpOl8cNf4ksIxVT1
      A04DGGuOVjO82VzecDZ+eZe82vpo4vPuo7VFordEEX6KV9uLntI/FcSjVKvrwIWY
      sumGDI+InpRuiqiNXmTP6ZrI6zOWDlU3cjFWj4GbSur2w81Zn8s288GHq/0BCHnr
      vHlwccAsy203qeNLMAsvn14cV2PJAiJmyKSKh1u2LJKn65fGxZgNmKR645Cdtvza
      E9cgxaEPRevzXqKBau3oNitHUwIDAQABoyEwHzAdBgNVHQ4EFgQU/UohHcQ/nJmT
      RKQHiY2NwOSbXZAwDQYJKoZIhvcNAQEEBQADggEBAIl93ePGxnQlqGDaAJi0sJ/F
      k2LRDwjH5nAs1Mdz8EwgnkqXVYCWmnkLErGp4m8+jVgi8GocLtwHxPkXE6MIOVLW
      KMiPNSRIfRafvFV5/qYSK03/O2pmpUxaFdgPg99qT7Zau2X6cwvLidamD2z5+zm4
      KVgW86yHQoBYXYrQf1oY3kcI6Jy8+wqJ/YWxI/sck/Bekxlw8NgGVBQjgrt/vL1z
      m9kkx7fX0W95ryiVCe/wiFu8Ubhk6Q5A0wUdBKz5RtECYMkT77YHA+YSWBfnQTUL
      T70iPeASI2Tm/zOXYWkXRUosRa9Pl9mq3Y92b6G+eO/Txmnmuao5QC6ctOEpvm4=
      -----END CERTIFICATE-----
    caCertificate: |
      -----BEGIN CERTIFICATE-----
      MIIDuzCCAqOgAwIBAgIEKoyOMTANBgkqhkiG9w0BAQQFADCBjTELMAkGA1UEBhMC
      VVMxETAPBgNVBAgTCFZpcmdpbmlhMRAwDgYDVQQHEwdGYWlyZmF4MQ4wDAYDVQQK
      EwVqYm9zczEPMA0GA1UECxMGcmVkaGF0MTgwNgYDVQQDDC8qLmFwcHMuY2x1c3Rl
      ci0xOGU1LjE4ZTUuc2FuZGJveDIzMy5vcGVudGxjLmNvbTAeFw0yMTAxMjAyMDM5
      MTJaFw00ODA2MDYyMDM5MTJaMIGNMQswCQYDVQQGEwJVUzERMA8GA1UECBMIVmly
      Z2luaWExEDAOBgNVBAcTB0ZhaXJmYXgxDjAMBgNVBAoTBWpib3NzMQ8wDQYDVQQL
      EwZyZWRoYXQxODA2BgNVBAMMLyouYXBwcy5jbHVzdGVyLTE4ZTUuMThlNS5zYW5k
      Ym94MjMzLm9wZW50bGMuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
      AQEAnPzk2KykgHDSmaEKse03Vl7IqFI9LGdNFHwCrFdEPVPi7uUGLWpjZxDJdLrT
      pWT8iVg28MZxDyAubWnUajPddQ2ZTXv6wHPPzpt2sk8hMDF8VpOl8cNf4ksIxVT1
      A04DGGuOVjO82VzecDZ+eZe82vpo4vPuo7VFordEEX6KV9uLntI/FcSjVKvrwIWY
      sumGDI+InpRuiqiNXmTP6ZrI6zOWDlU3cjFWj4GbSur2w81Zn8s288GHq/0BCHnr
      vHlwccAsy203qeNLMAsvn14cV2PJAiJmyKSKh1u2LJKn65fGxZgNmKR645Cdtvza
      E9cgxaEPRevzXqKBau3oNitHUwIDAQABoyEwHzAdBgNVHQ4EFgQU/UohHcQ/nJmT
      RKQHiY2NwOSbXZAwDQYJKoZIhvcNAQEEBQADggEBAIl93ePGxnQlqGDaAJi0sJ/F
      k2LRDwjH5nAs1Mdz8EwgnkqXVYCWmnkLErGp4m8+jVgi8GocLtwHxPkXE6MIOVLW
      KMiPNSRIfRafvFV5/qYSK03/O2pmpUxaFdgPg99qT7Zau2X6cwvLidamD2z5+zm4
      KVgW86yHQoBYXYrQf1oY3kcI6Jy8+wqJ/YWxI/sck/Bekxlw8NgGVBQjgrt/vL1z
      m9kkx7fX0W95ryiVCe/wiFu8Ubhk6Q5A0wUdBKz5RtECYMkT77YHA+YSWBfnQTUL
      T70iPeASI2Tm/zOXYWkXRUosRa9Pl9mq3Y92b6G+eO/Txmnmuao5QC6ctOEpvm4=
      -----END CERTIFICATE-----
    key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpAIBAAKCAQEAnPzk2KykgHDSmaEKse03Vl7IqFI9LGdNFHwCrFdEPVPi7uUG
      LWpjZxDJdLrTpWT8iVg28MZxDyAubWnUajPddQ2ZTXv6wHPPzpt2sk8hMDF8VpOl
      8cNf4ksIxVT1A04DGGuOVjO82VzecDZ+eZe82vpo4vPuo7VFordEEX6KV9uLntI/
      FcSjVKvrwIWYsumGDI+InpRuiqiNXmTP6ZrI6zOWDlU3cjFWj4GbSur2w81Zn8s2
      88GHq/0BCHnrvHlwccAsy203qeNLMAsvn14cV2PJAiJmyKSKh1u2LJKn65fGxZgN
      mKR645CdtvzaE9cgxaEPRevzXqKBau3oNitHUwIDAQABAoIBAEeFqDVXInMp86ju
      h9LcQlPlRwH4xcoPHjzw6r7d20cdisxQJ2pViAgSy9WUsIwv4CYqvI0hu6yqerx6
      dL4V9xU3Jtr4WxuHJ+v3RDKkfnhYc092YSouWubcTJiqxh3FUv+zMNvxIl7dQrJZ
      AXIgQXh6kYKko9qN4bXqTOazgg/YTUGwz76Nz9cKwlX+hKVcNmIvNdaT+wWKOIpp
      HbB1MSe5kQSVd/pVmIHgyBlXUaxifXnvnO1po29NtXeHPcD8UoE7VLo2QyNx1qMM
      DAxDTiyWY6m7IX9/VfVvuJkdU9ebdsbtwcmUKy5x0G/O+v+I85M8IJhFtzE78Btn
      TXrZIIECgYEA1qV5nDdl5JfYvXipPxC52qtVwWBuNkb6aT6+Ygibor9jLfCZz9TS
      ihSYyIvDPSE16JFIKmhh/q8GZVjKy2QlGfnKrQiLkRz8Kczq6y7FizvEzB9J71ia
      77N0sfK17PTyfYAprCLQ/dQLhKyjjSSFQJp2ncsbnV+fW2R+4WPPVyECgYEAuzuo
      BLPUg1SG06pDzCo60Vd42QtF8ltVZn9a6Mf0CmakYcDE/E4mpkd9POhq+GGvhLRW
      2gSjR2ggoYGEG8yFwx7/V59BxQ8UsQbqkW5SIw3UUMFQk5ssoBXj2AdllDfu8zPv
      kPuLmSkhV2BDtFlYZkNYxzcptwtzsgaTcOoAM/MCgYEA1kXkS6Uly3gmPqbIVZON
      5RPrDJsGCpr6ebvP9C9hpqrmCENKWKW882iySGj1Iv4XQa5eWy9OvB7fBKcJ8tZr
      Dy5EPE3ufZNwyw2sadCMFX057QdDGHLcYHNGCCohoIW52LzrXNJ4zRsz0GNC9bBC
      cYaA6O6MB6MgguykmL25iuECgYAN4y3iM2h22UUq2/0tXpCASImpJ6HniQi7koSu
      sW4Te2uD6KVzxWQufyz14JNWmwBGyo2KnD90I3AQKqge27usLldoK2LYd/bj7oxl
      fxZOjU8LMluEp0TXFuiQdHP/W2q41UhWq6G+GYPklDpRXTMmWqZyGFBayFmrgbtb
      669aKwKBgQDGV+yV1ZZ9x2bU0a6ZIeX4pDSjP1lO4a18ub6jImYjvCfDK7Xy16vh
      icDUnOZ/52nazrakdq+fLaT0xL16DEQ3XJhzU5CcrLyiaWu458zeoLtKc2Wugq8I
      F65uvIdjki0yiDl+f7zq+QRcmIroBqHkPiXe8cXbdPuBgOJVqV0vaw==
      -----END RSA PRIVATE KEY-----
    termination: edge