---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: {{ $.Values.name }}
  name: {{ $.Values.name }}
spec:
  replicas: {{ $.Values.replicas | default "1" }}
  revisionHistoryLimit: 10
  selector:
    deploymentConfig: {{ $.Values.name }}
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: {{ $.Values.name }}
        name: {{ $.Values.name }}
        deploymentConfig: {{ $.Values.name }}
      name: {{ $.Values.name }}-deploy
    spec:
      containers:
      - name: {{ $.Values.name }}
        image: {{ $.Release.Namespace }}/{{ $.Values.name }}
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8778
            protocol: TCP
          - containerPort: 9990
            protocol: TCP
        envFrom:
          - configMapRef:
              name: {{ $.Values.name }}
        resources: 
          limits:
              memory: 2G
            requests:
              memory: 1G
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  triggers:
  - type: ConfigChange
  - type: ImageChange
    imageChangeParams:
      automatic: true
      containerNames:
      - {{ $.Values.name }}
      from:
        kind: ImageStreamTag
        namespace: {{ $.Release.Namespace }}
        name: {{ $.Values.name }}:{{ $.Values.tag | default "latest" }}