apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $.Values.name }}-passthrough
spec:
  to:
    kind: Service
    name: {{ $.Values.name }}
  port:
    targetPort: 8443
  tls:
    termination: passthrough 