---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.name }}
  labels:
    app: {{ $.Values.name }}
    name: {{ $.Values.name }}
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: 8443-tcp
      protocol: TCP
      port: 8443
      targetPort: 8443
    - name: 8778-tcp
      protocol: TCP
      port: 8778
      targetPort: 8778
    - name: 9990-admin
      protocol: TCP
      port: 9990
  selector:
    deploymentConfig: {{ $.Values.name }}
  type: ClusterIP
  sessionAffinity: None