---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.name }}
  labels:
    app: {{ $.Values.name }}
    name: {{ $.Values.name }}
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    deploymentConfig: {{ $.Values.name }}
  type: ClusterIP
  sessionAffinity: None