---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: {{ $.Values.name }}
  name: {{ $.Values.name }}
spec:
  replicas: {{ $.Values.replicas | default "1" }}
  revisionHistoryLimit: 10
  selector:
    deploymentConfig: {{ $.Values.name }}
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: {{ $.Values.name }}
        name: {{ $.Values.name }}
        deploymentConfig: {{ $.Values.name }}
      name: {{ $.Values.name }}-deploy
    spec:
      containers:
      - name: {{ $.Values.name }}
        image: {{ $.Values.image.url }}:{{ $.Values.image.tag }}
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
            protocol: TCP
        envFrom:
          - configMapRef:
              name: {{ $.Values.name }}
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30