apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: jboss-git-repo
spec:
  params:
    - name: url
      value: '{{ $.Values.gitUrl }}'
    - name: revision
      value: {{ $.Values.branch }}
  type: git
